language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
branches:
  only:
    - release
    - gh-pages
env:
  - AUTHOR_TESTING=1
  - RELEASE_TESTING=1
notifications:
  recipients:
    - travisci@harleypig.com
  email:
    on_success: change
    on_failure: always
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
